import java.awt.CardLayout;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

/**
 *
 * @author Aisyahh
 */
public class PilihGambarCombobox extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarCombobox
     */
    public PilihGambarCombobox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        lblAnimeBiru = new javax.swing.JLabel();
        lblAnimeMerah = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        cbbxKue = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePanel.setLayout(new java.awt.CardLayout());

        lblAnimeBiru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cookies.png"))); // NOI18N
        imagePanel.add(lblAnimeBiru, "0");

        lblAnimeMerah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pancong.png"))); // NOI18N
        imagePanel.add(lblAnimeMerah, "1");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        cbbxKue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cookies", "Pancong" }));
        cbbxKue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbxKueItemStateChanged(evt);
            }
        });

        buttonPanel.add(cbbxKue);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbxKueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbxKueItemStateChanged
        CardLayout layout = (CardLayout) (imagePanel.getLayout());
        layout.show(imagePanel, String.valueOf(cbbxKue.getSelectedIndex()));
    }//GEN-LAST:event_cbbxKueItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarCombobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarCombobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> cbbxKue;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel lblAnimeBiru;
    private javax.swing.JLabel lblAnimeMerah;
    // End of variables declaration//GEN-END:variables
}
